### ISSUE TITLE
Growl Global throwing error on Win10 machines.

### ISSUE THREAD

**Issue by gokalpayaz** [WinUICommunity/WinUICommunity#22]
On Win11 machine, i have no issue running this code:

```
  Growl.AskGlobal("Do you want to install new version?", (s, e) =>
  {
      Task.WaitAll(Task.Run(async () =>
      {
          await updateService.DownloadRelease(assetId);
      }));
      updateService.InstallLatestRelease();
      App.Current.Exit();
      return true;
  });
```

 but i tried it on two different win10 machines and i receive this error:
`Value does not fall within the expected range.
`with the stack:
```
   at WinUICommunity.NativeMethods.DwmSetWindowAttribute(IntPtr hwnd, DWMWINDOWATTRIBUTE dwAttribute, UInt32& pvAttribute, UInt32 cbAttribute)
   at WinUICommunity.WindowHelper.SetWindowCornerRadius(IntPtr hwnd, DWM_WINDOW_CORNER_PREFERENCE cornerPreference)
   at WinUICommunity.WindowHelper.SetWindowCornerRadius(Window window, DWM_WINDOW_CORNER_PREFERENCE cornerPreference)
   at WinUICommunity.GrowlWindow.Init()
   at WinUICommunity.Growl.InitGrowlGlobal(GrowlInfo growlInfo, Boolean isForceSeverity, InfoBarSeverity forceSeverity)
   at WinUICommunity.Growl.AskGlobal(String title, Func`3 actionBeforeClose)
```
   
   
i also noticed that using regular Growl (not global) doesn't show anything.

**Comment by ghost1372** [comment]
Thank you for report, we are using some pinvoke for creating a transparent window, so I guess some of them are not supported in Windows 10. I will check more soon to fix the issue

**Comment by ghost1372** [comment]
Fixed in https://github.com/WinUICommunity/WinUICommunity/commit/a8b1bb4b6641ad8ad1e3d42af012d7fa327778f2

![image](https://github.com/WinUICommunity/WinUICommunity/assets/9213496/47912cd6-982c-4d65-ab70-a6f8a42daa33)
